services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT:-3001}
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    command: sh -c "yarn prisma migrate deploy && yarn start:prod"
    volumes:
      - ./prisma:/app/prisma

